# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get -qq update
          sudo apt-get -y --no-install-recommends install build-essential automake ncurses-dev cmake libcmocka0 git pkg-config autoconf libterm-ui-perl libasound2-dev libalsaplayer-dev openssl libssl-dev apt-utils xterm
          sudo apt-get -y install curl ncurses-dev libsctp-dev libpcap-dev ca-certificates sip-tester
          git clone -b 2.7.x --depth 1 https://github.com/pjsip/pjproject.git
          cd pjproject && ./configure --prefix=/usr && make dep && make && sudo make install

      - name: Build
        run: make

      - name: Test
        run: make test
